### ISSUE TITLE
JSONSerialization Error

### ISSUE THREAD

**Issue by sanjay-arya** [Rabbit-Converter/Rabbit-Swift#1]
`let rule:NSArray = (try! JSONSerialization.jsonObject(with: data!, options: [])) as! NSArray`
error: Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).

**Without try!**
`let rule:NSArray = JSONSerialization.jsonObject(with: data!, options: []) as! NSArray`
Error Domain=NSCocoaErrorDomain Code=3840 "Invalid escape sequence around character 36." UserInfo={NSDebugDescription=Invalid escape sequence around character 36.}

**Comment by saturngod** [comment]
fixed in the today commit.

**Comment by sanjay-arya** [comment]
Thanks bro

Best Regards,
Sanjay Arya

**Comment by sanjay-arya** [comment]
Thanks bro

**Comment by oaksoeshein** [comment]
Errors still exit in **pod 'Rabbit-Swift'**
